version: '3.1'

services:
    rancher:
        image: rancher/rancher:v2.3.5
        restart: always
        volumes:
            - var-lib-rancher:/var/lib/rancher
        ports:
          - 80:80
          - 443:443

volumes: 
    var-lib-rancher: